plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bench.examassist'
    compileSdk 34

    defaultConfig {
        applicationId "com.bench.examassist"
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName "2.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
